process index_bowtie2 {
    /*
    * This process indexes the reference genome using Bowtie2. The index files are stored in the
    * specified output directory.
    */
    publishDir "${params.output_dir}/bowtie2_index"
    input:
    path reference_genome
    val sample_name
    output:
    path "*.bt2" , emit: bowtie2_index_files
    path reference_genome , emit: reference_genome
    val sample_name, emit: sample_name
    script:
    """
    bowtie2-build --threads ${task.cpus} ${reference_genome} ${reference_genome}
    """
}

process align_bowtie2 {
    /*
    * This process aligns the input FASTQ files to the reference genome using Bowtie2. The output
    * is a BAM file containing the aligned reads.
    */
    publishDir "${params.output_dir}/bowtie2_alignment"
    input:
    val sample_name
    path reference_genome
    path reads
    path reference_genome_index_files
    output:
    path "${sample_name}_bowtie2.sam", emit: bowtie2_sam
    val paired ,emit: paired
    val sample_name, emit: sample_name
    path reads, emit: reads
    script:
    if (reads.size() == 2) {
        paired=true
        """
        bowtie2 \\
            -x ${reference_genome} \\
            -1 ${reads[0]} \\
            -2 ${reads[1]} \\
            -S ${sample_name}_bowtie2.sam \\
            --threads ${task.cpus} \\
        """
        
    }
    else {
        paired=false
        """
        bowtie2 \\
            -x ${reference_genome} \\
            -U ${reads[0]} \\
            -S ${sample_name}_bowtie2.sam \\
            --threads ${task.cpus} \\
        """
    }
}

process convert_sam_to_bam {
    /*
    * This process converts the SAM file generated by Bowtie2 to a BAM file using Samtools. The
    * output is a sorted BAM file.
    */
    publishDir "${params.output_dir}/samtools_conversion"
    input:
    path sam_file
    val sample_name
    output:
    path "${sam_file.baseName}.sorted.bam", emit: sorted_bam
    val sample_name, emit: sample_name
    script:
    """
    samtools view -bS ${sam_file} > ${sam_file.baseName}.bam
    """
}

process sort_bam {
    /*
    * This process sorts the BAM file using Samtools. The output is a sorted BAM file.
    */
    publishDir "${params.output_dir}/samtools_sort"
    input:
    path bam_file
    val sample_name
    output:
    path "${bam_file.baseName}.sorted.bam", emit: sorted_bam
    val sample_name, emit: sample_name
    script:
    """
    samtools sort ${bam_file} -o ${bam_file.baseName}.sorted.bam
    """
}

process convert_sam_to_sorted_bam {
    /*
    * This process converts the SAM file generated by Bowtie2 to a sorted BAM file using Samtools.
    * The output is a sorted BAM file.
    */
    publishDir "${params.output_dir}/samtools_conversion"
    input:
    path sam_file
    val sample_name
    val paired
    output:
    path "${sam_file.baseName}.sorted.bam", emit: sorted_bam
    val sample_name, emit: sample_name
    val paired, emit: paired
    script:
    """
    samtools view -bS ${sam_file} | samtools sort -o ${sam_file.baseName}.sorted.bam
    """
}

process get_unmapped_reads {
    /*
    * This process extracts unmapped reads from the BAM file using Samtools. The output is a FASTQ
    * file containing the unmapped reads.
    */
    publishDir "${params.output_dir}/samtools_unmapped"
    input:
    path bam_file
    val paired
    val sample_name
    output:
    path "${bam_file.baseName}.unmapped*fastq", emit: unmapped_reads
    val sample_name, emit: sample_name
    val paired, emit: paired
    script:
    if (paired) {
        """
        samtools view -b -f 12 -F 256 ${bam_file} | \
            samtools fastq -1 ${bam_file.baseName}.unmapped_1.fastq -2 ${bam_file.baseName}.unmapped_2.fastq
        """
    }
    else {
        """
        samtools view -b -f 4 ${bam_file} | \
            samtools fastq -f 4 > ${bam_file.baseName}.unmapped.fastq
        """
    }
}

process  get_mapped_reads{
    /*
    * This process extracts mapped reads from the BAM file using Samtools. The output is a FASTQ
    * file containing the mapped reads.
    */
    publishDir "${params.output_dir}/samtools_mapped"
    input:
    path bam_file
    val paired
    val sample_name
    output:
    tuple path("${bam_file.baseName}.mapped_1.fastq"), path("${bam_file.baseName}.mapped_2.fastq"), emit: mapped_fastq_1_2, optional: true
    path "${bam_file.baseName}.mapped.fastq", emit: mapped_fastq,optional: true
    val sample_name, emit: sample_name
    script:
    if (paired) {
        """
        samtools view -b -f 3 ${bam_file} | \
            samtools fastq -1 ${bam_file.baseName}.mapped_1.fastq -2 ${bam_file.baseName}.mapped_2.fastq
        """
    }
    else {
        """
        samtools view -b -F 4 ${bam_file} | \
            samtools fastq -1 ${bam_file.baseName}.mapped.fastq
        """
    }
}

process map_reads_fasta_pairs{
    /*
    * This process lumps indexing and mapping of reads to a genome. It  is useful for when we have read-genome pairs.
    */
    input:
    val(sample_name)
    path(reads)
    val(reference_fasta)
    val(paired)
    output:
    path reads, emit: reads
    path reference_fasta, emit: reference_fasta
    path "${sample_name}.sorted.bam", emit: sorted_bam
    val sample_name, emit: sample_name
    val paired, emit: paired

    script:
    """
    bowtie2-build --threads ${task.cpus} ${reference_fasta} ${reference_fasta}
    bowtie2 \\
        -x ${reference_fasta} \\
        -1 ${reads[0]} \\
        -2 ${reads[1]} \\
        -S ${sample_name}_bowtie2.sam \\
        --threads ${task.cpus} \\
    
    samtools view -bS ${sample_name}_bowtie2.sam | samtools sort -o ${sample_name}.sorted.bam
    """


}