FROM continuumio/anaconda3
RUN conda config --add channels conda-forge
RUN conda install bioconda::fastp -y 
RUN conda install bioconda::bowtie2 -y
RUN conda install bioconda::samtools -y
RUN conda install bioconda::megahit -y
RUN conda install bioconda::metabat2
mappe
# RUN conda install -c conda-forge -c bioconda gtdbtk=2.4.0
# RUN conda install coverm



