FROM continuumio/anaconda3
RUN conda config --add channels conda-forge
RUN conda create -n inStrain python=3.8 bioconda::instrain biopython=1.74 -y
RUN conda run -n inStrain conda install coverm samtools 
RUN conda run -n inStrain conda install -c bioconda bowtie2 
RUN conda run -n inStrain conda install numba
RUN conda run -n inStrain pip install drep
RUN wget https://github.com/biod/sambamba/releases/download/v1.0.1/sambamba-1.0.1-linux-amd64-static.gz
RUN gzip -d sambamba-1.0.1-linux-amd64-static.gz
RUN chmod +x sambamba-1.0.1-linux-amd64-static
RUN mv sambamba-1.0.1-linux-amd64-static /usr/local/bin/sambamba
RUN echo "source activate inStrain" >> ~/.bashrc
RUN conda init bash
ENV  PATH="/opt/conda/envs/inStrain/bin:$PATH"
RUN conda run -n inStrain pip install click aiofiles
ADD add_prefix_to_fasta.py /usr/local/bin/ 
RUN chmod +x  /usr/local/bin/add_prefix_to_fasta.py
RUN conda run -n inStrain conda install -c bioconda prodigal 
ADD compare_cosani.py /usr/local/bin/ 
RUN chmod +x  /usr/local/bin/compare_cosani.py
ADD NullModel.txt /data/
RUN conda run -n inStrain pip install instrain --upgrade